;[pytest]
;
;testpaths = testcases/
;markers =
;    single: single api test page
;    multiple: multiple api test page
;    negative: abnormal test case
;
;;xfail_strict = True
;
;log_cli = False
;
;addopts = --alluredir ./report

[pytest]

;the default search executes all use cases in the current directory
testpaths = ./testcases/

;change the default command line options
addopts = -v --reruns=0 --reruns-delay=5 -p no:faulthandler --instafail --tb=line --clean-alluredir --alluredir=./allure-results

;test class rule
python_classes = Test*

;test files rule
python_files = test*.py

;test functions rule
python_functions = test*

;ignore Warning
filterwarnings =
    ignore::DeprecationWarning

;Specify pytest to ignore some directories:
norecursedirs = .* build dist CVS _darcs {arch} *.egg venv src allure-results

;register label
markers =
    EP31
    EP32
