[default]
interface = "virtual"
;interface = 'virtual'<the name of the interface to use>
channel = <the channel to use by default>
bitrate = <the bitrate in bits/s to use by default>

[HS]
# All the values from the 'default' section are inherited
channel = 0
bitrate = 500000

[MS]
# All the values from the 'default' section are inherited
channel = 0
bitrate = 125000